name: redwood
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  transparent_image: "^0.1.0"
  url_launcher: "^3.0.2"
  firebase_analytics: "^1.0.1"
  firebase_messaging: "^1.0.3"
  cloud_firestore: "^0.7.4"
  firebase_database: "^1.0.3"
  firebase_auth: "^0.5.15"
  flutter_launcher_icons: "^0.5.2"
  scalable_image: "^1.1.1"
  quick_actions: "^0.2.1"
  flutter_youtube: "^1.0.1"
  firebase_core:
  shared_preferences: "^0.4.2"
  font_awesome_flutter: "^7.1.0"
  firebase_remote_config: "^0.0.5"
  connectivity: "^0.3.1"
  native_widgets: "^0.1.1+1"
  package_info: "^0.3.2"
  meta: "1.1.5"
  native_ui: "^0.0.4"
  #material_search: "^0.2.7"
  #google_sign_in: "^3.0.4"
  flutter_villains: "^1.0.0"
  flutter_localizations:
      sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  fonts:
       - family: Pacifico
         fonts:
           - asset: fonts/Pacifico.ttf

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - logo.gif
    - isontic.png
    - Map1.png
    - Map2.png
    - Map3.png
    - ni.jpg
    - Day1.png
    - Day2.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/
  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700